pool:
  vmImage: 'windows-2019'
  
trigger: none

# Configure this to run for both Debug and Release configurations
strategy:
  maxParallel: 4
  matrix:
    debug:
      BuildConfiguration: Debug
    release:
      BuildConfiguration: Release 

variables: 
  RestoreBuildProjects: '**/*.sln'

steps:
# Get the data files that are required for device detection automated system tests.
- powershell: |
   git lfs install
   ls
   git config --global --add filter.lfs.required true
   git config --global --add filter.lfs.smudge "git-lfs smudge -- %f"
   git config --global --add filter.lfs.process "git-lfs filter-process"
   git config --global --add filter.lfs.clean "git-lfs clean -- %f"
  displayName: 'Configure git lfs'

- checkout: self
  lfs: true
  submodules: recursive

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.3.1'
  inputs:
    versionSpec: 5.3.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(RestoreBuildProjects)'
    feedsToUse: 'select'
    vstsFeed: 'd2431f86-c1e6-4d8b-8d27-311cf3614847'

- task: VSBuild@1
  displayName: 'Build solutions'
  inputs:
    solution: '$(RestoreBuildProjects)'
    vsVersion: '15.0'
    platform: 'Any CPU'
    configuration: '$(BuildConfiguration)'
    clean: true
    
- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Visual Studio Test Platform Installer'
  inputs:
    versionSelector: latestStable
     
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - dotnet framework'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\net4*\*Tests*.dll
      !**\*TestAdapter*.dll
      !**\*TestFramework*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    otherConsoleOptions: '/Framework:Framework45 /logger:console;verbosity="normal"'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: true
    testRunTitle: 'framework-$(BuildConfiguration)'
    
- task: VSTest@2
  displayName: 'VsTest - testAssemblies - dotnet core'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\netcoreapp*\*Tests*.dll
      !**\*TestAdapter*.dll
      !**\*TestFramework*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1 /logger:console;verbosity="normal"'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: true
    testRunTitle: 'dotnetcore-$(BuildConfiguration)'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact' 
  

