//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiftyOne.Pipeline.AgentSignature {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiftyOne.Pipeline.AgentSignature.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No signature headers were present in the request.
        /// </summary>
        internal static string NoValueDetailAbsent {
            get {
                return ResourceManager.GetString("NoValueDetailAbsent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The signature did not carry this information.
        /// </summary>
        internal static string NoValueDetailNotSent {
            get {
                return ResourceManager.GetString("NoValueDetailNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The signature headers could not be read.
        /// </summary>
        internal static string NoValueDetailMalformed {
            get {
                return ResourceManager.GetString("NoValueDetailMalformed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No signature in the request was made for automated agent traffic.
        /// </summary>
        internal static string NoValueDetailWrongTag {
            get {
                return ResourceManager.GetString("NoValueDetailWrongTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The signature named no agent, so there was nowhere to fetch a key from.
        /// </summary>
        internal static string NoValueDetailNoAgent {
            get {
                return ResourceManager.GetString("NoValueDetailNoAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The signature was not verified so the directory was not read.
        /// </summary>
        internal static string NoValuePurposeNotRead {
            get {
                return ResourceManager.GetString("NoValuePurposeNotRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The agent does not say what its keys are for.
        /// </summary>
        internal static string NoValuePurposeNotStated {
            get {
                return ResourceManager.GetString("NoValuePurposeNotStated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No agent card available.
        /// </summary>
        internal static string NoValueNoCard {
            get {
                return ResourceManager.GetString("NoValueNoCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key directory at &apos;{0}&apos; could not be read because {1}.
        /// </summary>
        internal static string LogDirectoryFetchFailed {
            get {
                return ResourceManager.GetString("LogDirectoryFetchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The agent card at &apos;{0}&apos; could not be read because {1}.
        /// </summary>
        internal static string LogCardFetchFailed {
            get {
                return ResourceManager.GetString("LogCardFetchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The agent card registry at &apos;{0}&apos; could not be read because {1}.
        /// </summary>
        internal static string LogRegistryFetchFailed {
            get {
                return ResourceManager.GetString("LogRegistryFetchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key directory at &apos;{0}&apos; carried key times in milliseconds where the standard uses seconds.
        /// </summary>
        internal static string LogMillisecondKeyTimes {
            get {
                return ResourceManager.GetString("LogMillisecondKeyTimes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key directory at &apos;{0}&apos; had not been fetched after {1}ms, so this request reports the Timeout status.
        /// </summary>
        internal static string LogDirectoryPending {
            get {
                return ResourceManager.GetString("LogDirectoryPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A request was signed with the shared secret algorithm &apos;{0}&apos; using key id &apos;{1}&apos;.
        /// </summary>
        internal static string LogSharedSecretAlgorithm {
            get {
                return ResourceManager.GetString("LogSharedSecretAlgorithm", resourceCulture);
            }
        }
    }
}
